import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'vault-blue': '#0049E6',
        'terminal-gray': '#34424C',
        'on-error': '#690005',
        'on-secondary-fixed': '#241a00',
        'surface-container-high': '#2a2a2a',
        'inverse-on-surface': '#303030',
        'tertiary-fixed': '#e2e2e2',
        'surface-tint': '#c6c6c7',
        'secondary-container': '#f1c100',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#636565',
        'background': '#131313',
        'surface-container-low': '#1b1b1b',
        'on-background': '#e2e2e2',
        'inverse-primary': '#5d5f5f',
        'outline-variant': '#444748',
        'primary-fixed-dim': '#c6c6c7',
        'on-surface-variant': '#c4c7c8',
        'on-surface': '#e2e2e2',
        'on-secondary-container': '#665000',
        'error': '#ffb4ab',
        'on-primary-fixed': '#1a1c1c',
        'on-tertiary': '#2f3131',
        'surface-variant': '#353535',
        'on-primary': '#2f3131',
        'inverse-surface': '#e2e2e2',
        'surface-container-lowest': '#0e0e0e',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#454747',
        'tertiary-fixed-dim': '#c6c6c7',
        'surface-dim': '#131313',
        'surface-container-highest': '#353535',
        'primary': '#ffffff',
        'tertiary': '#ffffff',
        'secondary-fixed-dim': '#f1c100',
        'on-tertiary-fixed-variant': '#454747',
        'primary-container': '#e2e2e2',
        'on-secondary-fixed-variant': '#584400',
        'on-secondary': '#3d2f00',
        'on-tertiary-container': '#636565',
        'primary-fixed': '#e2e2e2',
        'tertiary-container': '#e2e2e2',
        'surface': '#131313',
        'grid-line': '#1A1D1F',
        'outline': '#8e9192',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-container': '#1f1f1f',
        'secondary': '#ffe08b',
        'surface-bright': '#393939',
        'secondary-fixed': '#ffe08b',
      },
      fontFamily: {
        'headline-lg-mobile': ['JetBrains Mono'],
        'data-point': ['JetBrains Mono'],
        'label-mono': ['JetBrains Mono'],
        'headline-xl': ['JetBrains Mono'],
        'headline-lg': ['JetBrains Mono'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '500' }],
        'data-point': ['18px', { lineHeight: '1.2', fontWeight: '400' }],
        'label-mono': ['11px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.05em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
      },
      spacing: {
        'margin-lg': '64px',
        'grid-gutter': '1px',
        'unit': '4px',
        'margin-md': '32px',
        'margin-sm': '16px',
      },
      borderRadius: {
        'DEFAULT': '0px',
        'lg': '0px',
        'xl': '0px',
        'full': '9999px',
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(to right, #1A1D1F 1px, transparent 1px), linear-gradient(to bottom, #1A1D1F 1px, transparent 1px)',
      },
      backgroundSize: {
        'grid': '40px 40px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'scan': {
          '0%': { top: '0' },
          '100%': { top: '100%' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'scan': 'scan 8s linear infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
